[env:esp32-s3-devkitc-1]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino

; CONFIGURAÇÃO "BREAKTHROUGH" - RL_V7 (PSRAM DESATIVADA, MAS TIMINGS OK)
; O WROOM-2 N8R8 EXIGE qio_opi para o flash de 8MB funcionar estavelmente,
; mesmo se desligarmos a PSRAM lógica.
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = dio
board_upload.flash_size = 8MB

; Serial Monitor
monitor_speed = 115200

; USB CDC Nativo JTAG (ID 1001)
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ; -D BOARD_HAS_PSRAM  <-- Mantemos desativado para liberar os pinos 33-42

lib_deps =
    bblanchon/ArduinoJson@7
    bogde/HX711@0.7.5
    robtillaart/I2CKeyPad@0.5.0
