[env:esp32-s3-devkitc-1]
platform = espressif32@^6.5.0
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor options
monitor_speed = 115200

; Extensões de Hardware e Segurança (S21)
board_build.flash_mode = qio
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D SECURE_BOOT_V2_ENABLED=1
    -D CONFIG_SECURE_BOOT=y
    -D CONFIG_SECURE_BOOT_V2_RSA_SUPPORT=y

lib_deps =
    bblanchon/ArduinoJson@7
    bogde/HX711@0.7.5
